# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [8]:
import pandas as pd
df = pd.read_csv("tic-tac-toe.csv")
display(df.head(5))
print(f"Shape: {df.shape}")

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

Shape: (958, 10)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

### 2.1 Split the training and test data.

In [16]:
x = df.drop(columns=['class'])
x = pd.get_dummies(x)
y = df['class'].astype(int)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

print(f"Training set shape: {x_train.shape}")
print(f"Test set shape: {x_test.shape}")

Training set shape: (766, 27)
Test set shape: (192, 27)

### 2.2 Create a Sequential model.

In [23]:
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.optimizers import Adam

model = Sequential()
model.add(Dense(50, activation='relu', input_shape=(x_train.shape[1],)))
model.add(Dense(20, activation='relu'))
model.add(Dense(2, activation='softmax'))
model.summary()

my_opt = Adam(learning_rate=0.001)
model.compile(loss='sparse_categorical_crossentropy',
              optimizer= my_opt,
              metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_27 (Dense)                │ (None, 50)             │         1,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 20)             │         1,020 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 2)              │            42 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,462 (9.62 KB)

 Trainable params: 2,462 (9.62 KB)

 Non-trainable params: 0 (0.00 B)

### 2.3 Train the model

In [24]:

history = model.fit(x_train, y_train,
                    batch_size=64,
                    epochs=20,
                    verbose=1,
                    validation_data=(x_test, y_test))

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 110ms/step - accuracy: 0.6423 - loss: 0.6540 - val_accuracy: 0.6458 - val_loss: 0.6353
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6632 - loss: 0.6156 - val_accuracy: 0.6562 - val_loss: 0.6098
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6802 - loss: 0.5910 - val_accuracy: 0.6979 - val_loss: 0.5872
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7102 - loss: 0.5679 - val_accuracy: 0.7188 - val_loss: 0.5650
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7350 - loss: 0.5458 - val_accuracy: 0.7344 - val_loss: 0.5449
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7493 - loss: 0.5265 - val_accuracy: 0.7708 - val_loss: 0.5245
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7598 - loss: 0.5066 - val_accuracy: 0.7812 - val_loss: 0.5121
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7637 - loss: 0.4832 - val_accuracy: 0.7656 - val_loss: 0.4934
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7637 - loss: 0.4652 - val_accuracy: 0.7604 - val_loss: 0.4788
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7755 - loss: 0.4487 - val_accuracy: 0.7812 - val_loss: 0.4660
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7807 - loss: 0.4286 - val_accuracy: 0.7865 - val_loss: 0.4446
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7963 - loss: 0.4065 - val_accuracy: 0.7917 - val_loss: 0.4374
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8185 - loss: 0.3854 - val_accuracy: 0.8073 - val_loss: 0.4119
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8394 - loss: 0.3624 - val_accuracy: 0.8177 - val_loss: 0.3956
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8655 - loss: 0.3366 - val_accuracy: 0.8281 - val_loss: 0.3718
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8864 - loss: 0.3128 - val_accuracy: 0.8438 - val_loss: 0.3485
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9060 - loss: 0.2870 - val_accuracy: 0.8698 - val_loss: 0.3231
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9243 - loss: 0.2612 - val_accuracy: 0.8958 - val_loss: 0.3025
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9321 - loss: 0.2356 - val_accuracy: 0.9115 - val_loss: 0.2702
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9465 - loss: 0.2158 - val_accuracy: 0.9115 - val_loss: 0.2590

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

### 3.1 Save Model

In [25]:
model.save("tic_tac_toe_model.keras")

### 3.2 Load Model

In [27]:
import tensorflow as tf

loaded_model = tf.keras.models.load_model("tic_tac_toe_model.keras")

### 3.3 Sample Predictions

In [30]:
sample_x = x_test.sample(5, random_state=42)
sample_y = y_test.loc[sample_x.index]

sample_pred = loaded_model.predict(sample_x)
display(sample_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 402ms/step

array([[0.7364114 , 0.26358855],
       [0.02670557, 0.97329444],
       [0.0177123 , 0.9822877 ],
       [0.14047013, 0.85952985],
       [0.17198871, 0.8280113 ]], dtype=float32)

In [32]:
import numpy as np

sample_pred_c = np.argmax(sample_pred, axis=1)
display(sample_pred_c)

array([0, 1, 1, 1, 1])

### 3.4 Comparision

In [33]:
results = sample_x.copy()

results["true_label"] = sample_y.values
results["predicted_label"] = sample_pred_c
results["correct"] = results["true_label"] == results["predicted_label"]

display(results)

,TL_b,TL_o,TL_x,TM_b,TM_o,TM_x,TR_b,TR_o,TR_x,ML_b,...,BL_x,BM_b,BM_o,BM_x,BR_b,BR_o,BR_x,true_label,predicted_label,correct
943,False,False,True,False,False,True,False,True,False,False,...,True,False,False,True,False,True,False,0,0,True
110,False,False,True,False,False,True,True,False,False,False,...,False,False,True,False,False,False,True,1,1,True
88,False,False,True,False,False,True,False,True,False,False,...,True,False,True,False,False,False,True,1,1,True
365,False,True,False,False,True,False,False,False,True,False,...,True,False,True,False,False,True,False,1,1,True
718,False,False,True,True,False,False,False,True,False,False,...,False,True,False,False,False,True,False,0,1,False

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [34]:
# Make a new model
model2 = Sequential()

model2.add(Dense(50, activation='relu', input_shape=(x_train.shape[1],)))
model2.add(Dense(20, activation='relu'))
model2.add(Dense(2, activation='softmax'))
model2.summary()

my_opt = Adam(learning_rate=0.001)
model2.compile(loss='sparse_categorical_crossentropy',
              optimizer= my_opt,
              metrics=['accuracy'])

# Train the model with more epochs
history = model2.fit(x_train, y_train,
                    batch_size=64,
                    epochs=30,
                    verbose=1,
                    validation_data=(x_test, y_test))

test_loss, test_accuracy = model2.evaluate(x_test, y_test, verbose=0)

print(f"Test loss: {test_loss:.4f}")
print(f"Test accuracy: {test_accuracy:.4f}")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                │ (None, 50)             │         1,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 20)             │         1,020 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 2)              │            42 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,462 (9.62 KB)

 Trainable params: 2,462 (9.62 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 99ms/step - accuracy: 0.4648 - loss: 0.7303 - val_accuracy: 0.5729 - val_loss: 0.6634
Epoch 2/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6540 - loss: 0.6375 - val_accuracy: 0.6771 - val_loss: 0.6290
Epoch 3/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6658 - loss: 0.6091 - val_accuracy: 0.6719 - val_loss: 0.6120
Epoch 4/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6789 - loss: 0.5885 - val_accuracy: 0.6927 - val_loss: 0.5912
Epoch 5/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7115 - loss: 0.5625 - val_accuracy: 0.7031 - val_loss: 0.5678
Epoch 6/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7337 - loss: 0.5418 - val_accuracy: 0.7240 - val_loss: 0.5496
Epoch 7/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7415 - loss: 0.5231 - val_accuracy: 0.7448 - val_loss: 0.5334
Epoch 8/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7441 - loss: 0.5027 - val_accuracy: 0.7552 - val_loss: 0.5156
Epoch 9/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7559 - loss: 0.4820 - val_accuracy: 0.7552 - val_loss: 0.4997
Epoch 10/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7598 - loss: 0.4633 - val_accuracy: 0.7552 - val_loss: 0.4841
Epoch 11/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7676 - loss: 0.4433 - val_accuracy: 0.7500 - val_loss: 0.4671
Epoch 12/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7728 - loss: 0.4250 - val_accuracy: 0.7656 - val_loss: 0.4506
Epoch 13/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7963 - loss: 0.4057 - val_accuracy: 0.7969 - val_loss: 0.4292
Epoch 14/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8120 - loss: 0.3829 - val_accuracy: 0.7969 - val_loss: 0.4131
Epoch 15/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8407 - loss: 0.3605 - val_accuracy: 0.8125 - val_loss: 0.3900
Epoch 16/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8551 - loss: 0.3374 - val_accuracy: 0.8281 - val_loss: 0.3723
Epoch 17/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8786 - loss: 0.3133 - val_accuracy: 0.8438 - val_loss: 0.3482
Epoch 18/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9073 - loss: 0.2859 - val_accuracy: 0.8542 - val_loss: 0.3242
Epoch 19/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9217 - loss: 0.2599 - val_accuracy: 0.8750 - val_loss: 0.2938
Epoch 20/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9452 - loss: 0.2319 - val_accuracy: 0.8906 - val_loss: 0.2689
Epoch 21/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9569 - loss: 0.2075 - val_accuracy: 0.9167 - val_loss: 0.2444
Epoch 22/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9661 - loss: 0.1808 - val_accuracy: 0.9323 - val_loss: 0.2191
Epoch 23/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9765 - loss: 0.1593 - val_accuracy: 0.9531 - val_loss: 0.1991
Epoch 24/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9804 - loss: 0.1402 - val_accuracy: 0.9479 - val_loss: 0.1786
Epoch 25/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9843 - loss: 0.1235 - val_accuracy: 0.9635 - val_loss: 0.1648
Epoch 26/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9883 - loss: 0.1085 - val_accuracy: 0.9635 - val_loss: 0.1495
Epoch 27/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9896 - loss: 0.0970 - val_accuracy: 0.9740 - val_loss: 0.1372
Epoch 28/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9896 - loss: 0.0862 - val_accuracy: 0.9688 - val_loss: 0.1308
Epoch 29/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9896 - loss: 0.0768 - val_accuracy: 0.9688 - val_loss: 0.1181
Epoch 30/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9883 - loss: 0.0698 - val_accuracy: 0.9740 - val_loss: 0.1064
Test loss: 0.1064
Test accuracy: 0.9740

**Which approach(es) did you find helpful to improve your model performance?**

In [35]:
# make model with more neurons, increse the epochs